/*
- Challenge Id: https://www.campapex.org/lesson/1337
- https://www.campapex.org/lesson/stringdeepdive/touppercase

*/

/* Example Submission:
String jobTitle = 'software engineer';
String formattedJobTitle = jobTitle.toUpperCase();
return formattedJobTitle;
*/

public class TestException extends Exception{} 

public class Solution { 
    String execute(){ 
        submission 
        return formattedJobTitle;
    }
} 

Solution sol = new Solution(); 

String result = sol.execute(); 

if(result == null || result != result.toUpperCase){
    throw new TestException('Expecting a String variable named \'formattedJobTitle\' and the values should be in uppercase using the toUpperCase() method.');
}
